[SSH Brute Force Detected]
search = index=botsv3 sourcetype=linux_secure _raw="*Invalid user*" earliest=0 | stats count by host | where count > 5 | head 1
dispatch.earliest_time = 0
dispatch.latest_time = now
enableSched = 1
cron_schedule = * * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
alert.suppress = 1
alert.suppress.period = 1h
alert.track = 0
action.webhook = 1
action.webhook.param.url = http://localhost:8001/api/agent/investigate

[Suspicious Outbound Connection]
search = index=botsv3 sourcetype=stream:tcp _raw="*91.207.175.249*" earliest=0 | stats count by src_ip | where count > 0 | head 1
dispatch.earliest_time = 0
dispatch.latest_time = now
enableSched = 1
cron_schedule = * * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
alert.suppress = 1
alert.suppress.period = 1h
alert.track = 0
action.webhook = 1
action.webhook.param.url = http://localhost:8001/api/agent/investigate

[Cryptomining Activity Detected]
search = index=botsv3 sourcetype="stream:dns" coinhive earliest=0 | stats count by host | where count > 0 | head 1
dispatch.earliest_time = 0
dispatch.latest_time = now
enableSched = 1
cron_schedule = * * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
alert.suppress = 1
alert.suppress.period = 1h
alert.track = 0
action.webhook = 1
action.webhook.param.url = http://localhost:8001/api/agent/investigate